/* mascot-shaders.js — GLSL for the Character department's rig.
 *
 * One program. The vertex stage is the house pattern from offering-material.js
 * (PANEL_VERT): a_pos arrives in CSS px, viewport space, y-down, and is mapped
 * to clip space with one uniform and no matrix. The fragment stage is the
 * whole rig: three capsules, a plate and a lens circle, evaluated as signed
 * distance fields against joint positions passed in as uniforms. No texture,
 * no mesh — the CPU in mascot.js owns the rig (six joint floats), the GPU only
 * shades the four-vertex bounding quad mascot.js recomputes every frame.
 *
 * ES module, consumed only by js/offerings/mascot.js via import.
 */

var MASCOT_VERT = [
  'attribute vec2 a_pos;      // CSS px, viewport space — the arm\'s own bounding quad',
  'uniform vec2 u_viewport;   // CSS px, width/height',
  'varying vec2 v_px;',
  '',
  'void main() {',
  '  v_px = a_pos;',
  '  vec2 clip = (a_pos / u_viewport) * 2.0 - 1.0;',
  '  clip.y = -clip.y;',
  '  gl_Position = vec4(clip, 0.0, 1.0);',
  '}'
].join('\n');

var MASCOT_FRAG = [
  'precision highp float;',
  '',
  'varying vec2 v_px;',
  '',
  'uniform vec2  u_base;       // plate centre, CSS px',
  'uniform vec2  u_elbow;',
  'uniform vec2  u_wrist;',
  'uniform vec2  u_head;       // lens centre',
  'uniform float u_plateR;',
  'uniform float u_upperR;',
  'uniform float u_foreR;',
  'uniform float u_headR;',
  'uniform float u_attention;  // 0..1, how awake the lens is',
  'uniform float u_alpha;',
  'uniform float u_tier;',
  '',
  '/* Capsule: distance from p to the segment a-b, minus radius r, plus the',
  '   point ON that segment nearest p — the capsule\'s own analytic gradient',
  '   is just normalize(p - nearest), so returning nearest here means the rim',
  '   light below needs no finite-difference sampling of the field at all. */',
  'float sdCapsule(vec2 p, vec2 a, vec2 b, float r, out vec2 nearest) {',
  '  vec2 pa = p - a, ba = b - a;',
  '  float h = clamp(dot(pa, ba) / max(dot(ba, ba), 1e-5), 0.0, 1.0);',
  '  nearest = a + ba * h;',
  '  return length(p - nearest) - r;',
  '}',
  '',
  '/* Polynomial smooth-min. A small k at a joint reads as a machined fillet',
  '   sleeving two parts together; a large k would melt the rig into a blob,',
  '   which is the one thing a mechanism must never look like. */',
  'float smin(float a, float b, float k) {',
  '  float h = clamp(0.5 + 0.5 * (b - a) / k, 0.0, 1.0);',
  '  return mix(b, a, h) - k * h * (1.0 - h);',
  '}',
  '',
  'void main() {',
  '  vec2 p = v_px;',
  '',
  '  /* One evaluation of the four primitives, not five: the outward direction',
  '     for lighting is read straight off whichever primitive is actually',
  '     closest (an exact analytic gradient, nearest.point already in hand),',
  '     rather than central-differencing the unioned field, which would need',
  '     four more evaluations of the same work just to get a normal. The only',
  '     place this is inexact is deep inside a joint fillet, where two',
  '     primitives are near-equidistant — a few px wide, always under the',
  '     smin blend, and never visible as a seam. */',
  '  /* The lens sits a stub beyond the wrist rather than fused to it — that is',
  '     the whole point, a small independently-lagging head on a neck — so an',
  '     explicit neck capsule bridges wrist to head. Without it the two only',
  '     meet through the smin blend radius, which is nowhere near wide enough',
  '     to span the actual gap and the head reads as a separate floating ball.',
  '  */',
  '  vec2 nUpper, nFore, nNeck;',
  '  float dPlate = length(p - u_base) - u_plateR;',
  '  float dUpper = sdCapsule(p, u_base, u_elbow, u_upperR, nUpper);',
  '  float dFore  = sdCapsule(p, u_elbow, u_wrist, u_foreR, nFore);',
  '  float dNeck  = sdCapsule(p, u_wrist, u_head, u_foreR * 0.6, nNeck);',
  '  float dHead  = length(p - u_head) - u_headR;',
  '',
  '  float body = smin(dPlate, dUpper, 6.0);',
  '  body = smin(body, dFore, 5.0);',
  '  body = smin(body, dNeck, 4.0);',
  '  float d = smin(body, dHead, 7.0);',
  '',
  '  float aa = 1.25;',
  '  float edge = 1.0 - smoothstep(-aa, aa, d);',
  '  if (edge <= 0.003) discard;',
  '',
  '  float dMin = min(min(dPlate, dUpper), min(min(dFore, dNeck), dHead));',
  '  vec2 outward;',
  '  if (dMin == dPlate) outward = normalize(p - u_base);',
  '  else if (dMin == dUpper) outward = normalize(p - nUpper);',
  '  else if (dMin == dFore) outward = normalize(p - nFore);',
  '  else if (dMin == dNeck) outward = normalize(p - nNeck);',
  '  else outward = normalize(p - u_head);',
  '',
  '  /* Machined-metal base: dark, with a faint low-frequency variation so it',
  '     does not read as a flat cutout. Cheap — one sine, no texture. */',
  '  float variance = 0.5 + 0.5 * sin(p.x * 0.02 + p.y * 0.017);',
  '  vec3 metal = mix(vec3(0.075, 0.084, 0.104), vec3(0.155, 0.172, 0.205), variance);',
  '',
  '  float distIn = -d; // positive moving inward from the silhouette edge',
  '  vec3 col = metal * mix(0.62, 1.0, clamp(distIn / 10.0, 0.0, 1.0));',
  '',
  '  vec3 accent = vec3(0.3098, 0.8471, 0.7686); // #4FD8C4, the site\'s one accent',
  '',
  '  /* Fake-round bevel, the same trick a lathe-turned edge actually does to',
  '     light: right at the silhouette the surface is treated as turning fully',
  '     away from the camera (n.z -> 0, grazing — where a rim wants to live),',
  '     and by BEVEL px inside it has turned to face the camera flat (n.z -> 1,',
  '     matte). This is what gives a flat 2D SDF a lit top edge instead of a',
  '     uniform glow band: the light only catches the part of the bevel that',
  '     is actually turned toward it, the same job Fresnel does for the glass',
  '     panels off their real 3D normal. Tier 1 skips the extra ALU for a',
  '     cheaper, flatter distance-only band instead of disappearing. */',
  '  if (u_tier > 1.5) {',
  '    float BEVEL = 9.0;',
  '    float t = clamp(distIn / BEVEL, 0.0, 1.0);',
  '    vec3 n = normalize(vec3(outward * (1.0 - t), t + 0.05));',
  '    vec3 lightDir = normalize(vec3(-0.35, -0.85, 0.45)); // from upper-left, like the glass',
  '    float diff = max(dot(n, lightDir), 0.0);',
  '    float rim = pow(1.0 - t, 2.0);',
  '    col += vec3(0.85, 0.92, 0.98) * diff * diff * 0.85;',
  '    col += accent * rim * 0.30;',
  '  } else {',
  '    float rim = (1.0 - smoothstep(0.0, 5.0, distIn));',
  '    col += vec3(0.55, 0.72, 0.68) * rim * 0.22;',
  '  }',
  '',
  '  /* The lens: one accent-coloured light in the head, brightening with',
  '     attention. This is the only saturated colour on the whole rig — the',
  '     one place the eye is meant to land. */',
  '  float dLens = length(p - u_head) - u_headR * 0.55;',
  '  float lens = 1.0 - smoothstep(-2.0, 2.0, dLens);',
  '  col = mix(col, accent, lens * mix(0.30, 0.92, u_attention));',
  '  col += accent * lens * u_attention * 0.55;',
  '',
  '  /* Premultiplied, to match the Stage baseline blend (ONE,',
  '     ONE_MINUS_SRC_ALPHA), same convention as offering-material.js. */',
  '  float a = edge * u_alpha;',
  '  gl_FragColor = vec4(col * a, a);',
  '}'
].join('\n');

export { MASCOT_VERT, MASCOT_FRAG };
